--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ABOUTUS
--------------------------------------------------------

  CREATE TABLE "ADPOOL"."ABOUTUS" 
   (	"U_NO" NUMBER(*,0), 
	"U_NAME" VARCHAR2(50 BYTE), 
	"U_EMAIL" VARCHAR2(50 BYTE), 
	"U_DATE" DATE, 
	"U_URL" VARCHAR2(50 BYTE), 
	"U_ROLE" VARCHAR2(500 BYTE), 
	"U_BIRTH" DATE, 
	"U_PROJECT" VARCHAR2(500 BYTE), 
	"U_PIC" VARCHAR2(200 BYTE), 
	"U_EXP" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ADPOOL.ABOUTUS
SET DEFINE OFF;
Insert into ADPOOL.ABOUTUS (U_NO,U_NAME,U_EMAIL,U_DATE,U_URL,U_ROLE,U_BIRTH,U_PROJECT,U_PIC,U_EXP) values (1,'a','bzuz@hotmail.com',to_date('18/07/25','RR/MM/DD'),'https://www.naver.com/','d',to_date('18/07/04','RR/MM/DD'),'d','0','a');
Insert into ADPOOL.ABOUTUS (U_NO,U_NAME,U_EMAIL,U_DATE,U_URL,U_ROLE,U_BIRTH,U_PROJECT,U_PIC,U_EXP) values (2,'최승호','bzuzsound@gmail.com',to_date('18/07/25','RR/MM/DD'),'http://127.0.0.1/adpool/main','개발',to_date('86/01/21','RR/MM/DD'),'team2','0','없음');
--------------------------------------------------------
--  DDL for Index SYS_C007683
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADPOOL"."SYS_C007683" ON "ADPOOL"."ABOUTUS" ("U_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ABOUTUS
--------------------------------------------------------

  ALTER TABLE "ADPOOL"."ABOUTUS" ADD PRIMARY KEY ("U_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADPOOL"."ABOUTUS" MODIFY ("U_PIC" NOT NULL ENABLE);
  ALTER TABLE "ADPOOL"."ABOUTUS" MODIFY ("U_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "ADPOOL"."ABOUTUS" MODIFY ("U_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ADPOOL"."ABOUTUS" MODIFY ("U_NAME" NOT NULL ENABLE);
  ALTER TABLE "ADPOOL"."ABOUTUS" MODIFY ("U_NO" NOT NULL ENABLE);
